#! /bin/sh

# Auto start
sxhkd &
~/.config/polybar/./launch.sh --hack
picom &
feh --bg-fill ~/Pictures/Wallpapers/lost.jpg

# BSPWM configs
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off

# Disable X cursor
xsetroot -cursor_name left_ptr &
